apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-with-helm
  labels:
    app: wordpress
#    chart: {{ template "helm-guestbook.chart" . }}
    release: latest
#    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wordpress
      release: latest
  template:
    metadata:
      labels:
        app: wordpress
        release: latest
    spec:
      containers:
        - name: wordpress
          image: https://charts.bitnami.com/bitnami/wordpress
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:

